<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AutoCADTargetFramework Condition="'$(AutoCADTargetFramework)'==''">net8.0</AutoCADTargetFramework>
    <TargetFramework>$(AutoCADTargetFramework)</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CadTranslation.Contracts\CadTranslation.Contracts.csproj" />
  </ItemGroup>
</Project>
